### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by polosskevin** [polosskevin/zia#15]

**Comment by polosskevin** [comment]
first the two mendatory modules, which are openssl and php modules

**Comment by polosskevin** [comment]
@MickaToast @fraiss-c  how is going ?

**Comment by MickaToast** [comment]
@polosskevin will try to look this week

**Comment by polosskevin** [comment]
i will take in charge openssl as it is a part of the network implementation.

**Comment by MickaToast** [comment]
@polosskevin still hasn't started to focus on the projet, I'm finishing another project and will try to look into this asap, should start this weekend

**Comment by fraiss-c** [comment]
@polosskevin If you hande the SSL module, the second one to handle is PHP, and we are two. Which module you wanna see implemented in third ?

**Comment by polosskevin** [comment]
You can propose one, we're not limited to 2. Providing a list of possible module could be a good solution.

**Comment by fraiss-c** [comment]
@polosskevin I'm on module_dumpio which is a logger

https://httpd.apache.org/docs/2.4/mod/mod_dumpio.html
