### ISSUE TITLE
reload modules

### ISSUE THREAD

**Issue by polosskevin** [polosskevin/zia#17]
in charge of providing a class which reload the differentsg http modules in the directory. It has to provide asynchrone api.

**Comment by florian-vuillemot** [comment]
How this process is launch ? Signal ? Hook or callback ? File update ?

**Comment by polosskevin** [comment]
i think POSIX propose an api with a filedescriptor to watch but i'm not sure. a call back would be perfect

**Comment by polosskevin** [comment]
but any proposition is to be discussed

**Comment by polosskevin** [comment]
how is it going ?

**Comment by florian-vuillemot** [comment]
Found it: http://modwsgi.readthedocs.io/en/develop/user-guides/reloading-source-code.html
They use a signal (SIGINT) for reload modules.

**Comment by florian-vuillemot** [comment]
I proposed to use a signal for reloading, SIGINT is on window and linux.
Are you ok ?
