### ISSUE TITLE
parsing http request

### ISSUE THREAD

**Issue by polosskevin** [polosskevin/zia#18]

**Comment by beurie-v** [comment]
I'd say between 1 and 2 weeks of work are needed, depending on the problems encountered during development

**Comment by polosskevin** [comment]
Ok, here is a link to a basic implementation of a http server with parsing in it if it might help:
http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/examples/cpp11_examples.html#boost_asio.examples.cpp11_examples.http_server

**Comment by beurie-v** [comment]
Started to take a look at external librairies to do it for us, any idea if they are allowed ?

**Comment by polosskevin** [comment]
nothing is allowed

**Comment by beurie-v** [comment]
Ok, have a nice day

**Comment by polosskevin** [comment]
thx you too

**Comment by polosskevin** [comment]
kiss

**Comment by polosskevin** [comment]
how is it going @beurie-v ?

**Comment by beurie-v** [comment]
Not working on it yet, deadlines on other projets are more crucial
