### ISSUE TITLE
configuration_file

### ISSUE THREAD

**Issue by polosskevin** [polosskevin/zia#3]
add library to use on configuration file and start the abstraction of the configuration

**Comment by polosskevin** [comment]
testing rapidjson

**Comment by florian-vuillemot** [comment]
What's the format ?

**Comment by polosskevin** [comment]
json

**Comment by florian-vuillemot** [comment]
We have to doc it ?

**Comment by polosskevin** [comment]
we don't know yet what are the fields in it. I think we should focus on other issues first
